# TensorFlow
## Hello World

In [1]:
import tensorflow as tf
import numpy as np
tf.logging.set_verbosity(tf.logging.ERROR)

In [2]:
tf.version.VERSION

'1.13.1'

In [3]:
m = tf.constant(np.arange(1, 12), shape=[4,3], dtype=tf.float32)
print(m)

Tensor("Const:0", shape=(4, 3), dtype=float32)


In [4]:
n = tf.random_uniform([3,4], seed=888)
print(n)

Tensor("random_uniform:0", shape=(3, 4), dtype=float32)


In [5]:
result = tf.matmul(m, n)
with tf.Session() as ss:
    print(ss.run(result))

[[ 2.9368987  2.113493   2.048277   2.08671  ]
 [ 7.02995    6.137428   5.3143373  4.4081416]
 [11.123002  10.161362   8.580399   6.7295732]
 [14.568766  14.110989  11.497057   8.446618 ]]


## TF Graph

In [6]:
# tf.get_default_graph
new_graph = tf.Graph()
with new_graph.as_default():
    var = tf.get_variable('var', shape=[2,3], initializer=tf.zeros_initializer())
    assert var.graph is new_graph
with tf.Session(graph=new_graph) as ss:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=tf.AUTO_REUSE):
        print(ss.run(tf.get_variable('var')))
# device of graph
# with new_graph.device('/device:GPU:0'):

[[0. 0. 0.]
 [0. 0. 0.]]
