# TensorFlow
## Hello World

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
m = tf.constant(np.arange(1, 12), shape=[4,3], dtype=tf.float32)
print(m)

Tensor("Const:0", shape=(4, 3), dtype=float32)


In [3]:
n = tf.random_uniform([3,4])
print(n)

Tensor("random_uniform:0", shape=(3, 4), dtype=float32)


In [4]:
result = tf.matmul(m, n)
with tf.Session() as ss:
    print(ss.run(result))

[[ 3.4792995  4.301923   3.7602973  2.5596242]
 [ 8.341598  10.519694   9.580165   7.4605136]
 [13.203896  16.737465  15.400032  12.3614025]
 [17.277737  22.170605  20.524305  17.197365 ]]
