# Julia
## Install IJulia

[IJulia](https://github.com/JuliaLang/IJulia.jl) is Jupyter kernel for Julia

Install [Julia](https://julialang.org/) firstly, then in Julia REPL
```julia
julia>
using Pkg
Pkg.add("IJulia")
Pkg.build("ZMQ")
Pkg.build("IJulia")
```
and finally start the notebook with ```jupyter notebook```

[Learn Julia in Y minutes](https://learnxinyminutes.com/docs/julia/)

Enjoy!

Julia Version 1.1.0

Just type `?` for help, or [Julia Docs](https://docs.julialang.org)

## Contents
- [Datatypes](#Julia-Datatypes,-Variables-and-Collections)
- [Functions](#Julia-Functions,-Control-Flow-and-Types)
- [Parallel Computing](#Parallel-Computing)
- [Multi-dimensional Arrays](#Multi-dimensional-Arrays)

In [1]:
println("Hello Julia")

Hello Julia


# Julia Datatypes, Variables and Collections

In [2]:
Int,Int8,Int16,Int32,Int64,Int128,UInt,UInt8,UInt16,UInt32,UInt64,UInt128,Float16,Float32,Float64,Inf,NaN,BigInt,BigFloat

(Int64, Int8, Int16, Int32, Int64, Int128, UInt64, UInt8, UInt16, UInt32, UInt64, UInt128, Float16, Float32, Float64, Inf, NaN, BigInt, BigFloat)

In [3]:
typemin(Int), typemax(Int)

(-9223372036854775808, 9223372036854775807)

In [4]:
typeof(1),typeof(0x1),typeof(0x123),typeof(0b101),typeof(2 + 1im),typeof(2 // 3)

(Int64, UInt8, UInt16, UInt8, Complex{Int64}, Rational{Int64})

In [5]:
true, false

(true, false)

In [6]:
const x = 8
2x^2 - 6.3(x+4) + 5

57.400000000000006

In [7]:
zero(x), zero(Float64)

(0, 0.0)

In [8]:
2 < x < 9

true

In [9]:
let x::Int32 = 8; x,typeof(x) end

(8, Int32)

In [10]:
gcd(128,48), lcm(128, 48)

(16, 384)

In [11]:
hypot(8,9)

12.041594578792296

In [12]:
# complex
5(1 + 2im)*(2 - 3im)

40 + 5im

In [13]:
# fraction
1 + 6//16

11//8

In [14]:
bitstring(888)

"0000000000000000000000000000000000000000000000000000001101111000"

In [15]:
bitstring(0.3)

"0011111111010011001100110011001100110011001100110011001100110011"

In [16]:
s="julia"
typeof(s), typeof('a')

(String, Char)

In [17]:
"good" > "bye"

true

In [18]:
# based on 1
s[1], s[end], s[2:4]

('j', 'a', "uli")

In [19]:
Int('A'), Char(89)

(65, 'Y')

In [20]:
h = "Hello $s $(3+5)"

"Hello julia 8"

In [21]:
repeat("*",10), length(h)

("**********", 13)

In [22]:
using Printf
@printf "demo %0.2f\n" 5.3

demo 5.30


In [23]:
printstyled(h, color=:blue)

Hello julia 8

In [24]:
a = [8,6,4]

3-element Array{Int64,1}:
 8
 6
 4

In [25]:
b = Int32[7;1;9]

3-element Array{Int32,1}:
 7
 1
 9

In [26]:
push!(a, 8)

4-element Array{Int64,1}:
 8
 6
 4
 8

In [27]:
pop!(a)

8

In [28]:
append!(a, b)

6-element Array{Int64,1}:
 8
 6
 4
 7
 1
 9

In [29]:
popfirst!(a)

8

In [30]:
pushfirst!(a, 7)

6-element Array{Int64,1}:
 7
 6
 4
 7
 1
 9

In [31]:
# Remove elements from an array by index with splice
splice!(a, 2)

6

In [32]:
length(a), in(2, a)

(5, false)

In [33]:
sort(a)

5-element Array{Int64,1}:
 1
 4
 7
 7
 9

In [34]:
sort!(a)

5-element Array{Int64,1}:
 1
 4
 7
 7
 9

In [35]:
matrix = [3 6 1; 4 2 5]

2×3 Array{Int64,2}:
 3  6  1
 4  2  5

In [36]:
sort(matrix, dims=1)

2×3 Array{Int64,2}:
 3  2  1
 4  6  5

In [37]:
sort(matrix, dims=2)

2×3 Array{Int64,2}:
 1  3  6
 2  4  5

In [38]:
[1:5],[1:5;]

(UnitRange{Int64}[1:5], [1, 2, 3, 4, 5])

Tuples like arrays, but are immutable.

In [39]:
# swap values
m, n = (4 ,5)
m, n = n, m

(5, 4)

Dictionaries store unordered mappings

In [40]:
dict = Dict("one" => 1, "two" => 2, "three" => 3)

Dict{String,Int64} with 3 entries:
  "two"   => 2
  "one"   => 1
  "three" => 3

In [41]:
dict["two"], keys(dict), values(dict)

(2, ["two", "one", "three"], [2, 1, 3])

In [42]:
get(dict, "three", 4)

3

In [43]:
get(dict, "four", 4)

4

Sets store unordered, unique values

In [44]:
seta = Set([1, 2, 2, 3, 4])

Set([4, 2, 3, 1])

In [45]:
setb = Set([3, 4, 5, 6])

Set([4, 3, 5, 6])

In [46]:
intersect(seta, setb), union(seta, setb), setdiff(seta, setb)

(Set([4, 3]), Set([4, 2, 3, 5, 6, 1]), Set([2, 1]))

# Julia Functions, Control Flow and Types
Julia functions are first class

Functions support varargs, positional arguments, keyword arguments and multiple dispatch(overload)

Names of functions and macros are in lower case, without underscores.

Functions that modify their inputs have names that end in !

In [47]:
function bar(x,y)
  x + y
end

bar (generic function with 1 method)

In [48]:
foo(x,y) = 3x^2 + 8y
foo(3,5)

67

In [49]:
map(x -> x^2 + 2x - 1, [8, 4.5, 3.3])

3-element Array{Float64,1}:
 79.0 
 28.25
 16.49

In [50]:
# mulit line
map([-8, 4, -3, 0]) do x
    if x < 0 && iseven(x)
        return 0
    elseif x == 0
        return 1
    else
        return x
    end
end

4-element Array{Int64,1}:
  0
  4
 -3
  1

In [51]:
z = (x = 1; y = 2; x + y)

3

In [52]:
begin
    x = 1; 
    y = 2;
    if x < y
        x + y
    else
        x * y
    end
end

3

In [53]:
min(x, y) = x < y ? x : y; min(3,4)

3

In [54]:
# error() throw ErrorException
# warn() info()
function factorial(n::Int)
    n == 0 && return 1
    n >= 0 || error("n must be non-negative")
    n * factorial(n-1)
end
factorial(8)

40320

In [55]:
try factorial(-4)
catch e
    println("occur error ", e)
end

occur error ErrorException("n must be non-negative")


Functions Multiple dispatch

In [56]:
foo(x::Float64, y::Float64) = 2x + y, "float version"
foo(x::Int, y::Int) = 2x + y, "int version"
foo(3.2, 2.7), foo(4, 7)

((9.100000000000001, "float version"), (15, "int version"))

In [57]:
# list all methods of function
methods(foo)

# 3 methods for generic function "foo":
[1] foo(x::Int64, y::Int64) in Main at In[56]:2
[2] foo(x::Float64, y::Float64) in Main at In[56]:1
[3] foo(x, y) in Main at In[48]:1

In [58]:
# Parametric Methods
isSameType(x::T, y::T) where {T} = true
isSameType(x, y) = false
isSameType(2, 3.4), isSameType(2, 6)

(false, true)

In [59]:
summ = 0
# Range
for i = 1:5
    summ += i
end
println(summ)

15


In [60]:
for i in [8,5,3]
    summ += i
end
println(summ)

31


In [61]:
function varargs(args...)
    return args
end
varargs(4, 9, 2)

(4, 9, 2)

In [62]:
varargs([4, 9, 2]...)

(4, 9, 2)

In [63]:
# lambda, anonymous functions
(x -> x > 2)(3)

true

In [64]:
# Closure
# keyword return is optional
function adder()
    x = 0
    function ()
        x += 1
        x
    end
end
add = adder()
add(), add(), add()

(1, 2, 3)

In [65]:
# list comprehensions
[2i for i in [1, 2, 3] if i&1==1 ]

2-element Array{Int64,1}:
 2
 6

Julia Types like records or structs

DataType is the type that represents types, including itself.

In [66]:
typeof(DataType)

DataType

In [67]:
abstract type Super end

struct is immutable by default, [story of struct and type](https://github.com/JuliaLang/julia/pull/20418)

In [68]:
struct Point <: Super
    x::Float64
    y::Float64
end
p = Point(3.2, 4.8)

Point(3.2, 4.8)

In [69]:
p.x, p.y

(3.2, 4.8)

In [70]:
# outer constructor
Point(x) = Point(x,x)
Point(3)

Point(3.0, 3.0)

In [71]:
subtypes(Point), supertype(Point), subtypes(Number), supertype(Number)

(Type[], Super, Any[Complex, Real], Any)

int type hierarchy: 

Int => Signed => Integer => Real => Number => Any

All of these type, except for Int, are abstract.

In [72]:
# bitstype was renamed to primitive type
primitive type short <: Signed 16 end
let sh:short = 8 end

In [73]:
abstract type Mammal end
mutable struct Cat <: Mammal
    color::String
    # inner constructor
    Cat() = new("Inner")
    Cat(x) = new(x)
end
Cat("Black"), Cat()

(Cat("Black"), Cat("Inner"))

In [74]:
# outer constructor
Cat() = Cat("White")
Cat()

Cat("White")

In [75]:
IntOrString = Union{Int,String}

Union{Int64, String}

In [76]:
struct Pointy{T <: Real}
    x::T
    y::T
end
pt = Pointy{Int32}(3,4)

Pointy{Int32}(3, 4)

In [77]:
Pointy <: Any

true

In [78]:
Int32 <: Signed, Pointy{Int32} <: Pointy{Signed}

(true, false)

code_native() function can get assembly code

In [79]:
area(r) = pi * r * r 
code_native(area, (Int32,), syntax = :intel)

	.text
; ┌ @ In[79]:1 within `area'
	push	rbp
	mov	rbp, rsp
; │┌ @ operators.jl:502 within `*' @ promotion.jl:314
; ││┌ @ promotion.jl:284 within `promote'
; │││┌ @ promotion.jl:261 within `_promote'
; ││││┌ @ number.jl:7 within `convert'
; │││││┌ @ float.jl:60 within `Type'
	vcvtsi2sd	xmm0, xmm0, ecx
	movabs	rax, 341947456
; ││└└└└
; ││ @ operators.jl:502 within `*' @ float.jl:399
	vmulsd	xmm1, xmm0, qword ptr [rax]
	vmulsd	xmm0, xmm1, xmm0
; │└
	pop	rbp
	ret
	nop	dword ptr [rax]
; └


# Parallel Computing
## Julia [Tasks](https://docs.julialang.org/en/v1/manual/control-flow/#man-tasks-1) (aka Coroutines)
Channels manage communication and data synchronization

Channels support take!, fetch, put!, close

**NOTE**: current version of Julia multiplexes all tasks onto a single OS thread

Future versions of Julia may support scheduling of tasks on multiple threads

In [80]:
function producer(c::Channel)
    put!(c, "start")
    for n = 1:3
        put!(c, 2n)
    end
    put!(c, "stop")
end
c = Channel(producer)
take!(c)

"start"

In [81]:
for x in Channel(producer)
    println(x)
end

start
2
4
6
stop


In [82]:
ch = Channel{Int}(10)
foreach(i->put!(ch, i), 1:3)
close(ch)
[i for i in ch]

3-element Array{Int64,1}:
 1
 2
 3

A simple example using channels for inter-task communication

We start 4 tasks to process data from a single jobs channel. Jobs, identified by an id (job_id), are written to the channel. Each task in this simulation reads a job_id, waits for a random amount of time and writes back a tuple of job_id and the simulated time to the results channel. Finally all the results are printed out.

In [83]:
const jobs = Channel{Int}(32)
const results = Channel{Tuple}(32)
function do_work()
    for job_id in jobs
        exec_time = rand()
        sleep(exec_time) # simulates elapsed time doing actual work
        put!(results, (job_id, exec_time))
    end
end
function make_jobs(n)
    for i in 1:n
        put!(jobs, i)
    end
end
n = 12
# feed the jobs channel with "n" jobs
@async make_jobs(n)
# start 4 tasks to process requests in parallel
for i in 1:4
    @async do_work()
end
# print out results
@elapsed while n > 0
    job_id, exec_time = take!(results)
    println("$job_id finished in $(round(exec_time; digits=2)) seconds")
    global n = n - 1
end

4 finished in 0.38 seconds
2 finished in 0.49 seconds
1 finished in 0.52 seconds
3 finished in 0.86 seconds
7 finished in 0.6 seconds
6 finished in 0.8 seconds
5 finished in 0.93 seconds
9 finished in 0.24 seconds
11 finished in 0.22 seconds
10 finished in 0.38 seconds
8 finished in 0.99 seconds
12 finished in 0.6 seconds


2.046906118

## Multi-Threading
[experimental] Base.Threads module

In [84]:
# controlled by env JULIA_NUM_THREADS, default is 1
Threads.nthreads()

1

In [85]:
Threads.threadid()

1

In [86]:
ids = zeros(10)
Threads.@threads for i = 1:10
    ids[i] = Threads.threadid()
end

In [87]:
atm = Threads.Atomic{Int}(0)
oldatm = Threads.atomic_add!(atm, 8)
oldatm, atm.value

(0, 8)

## Distributed Processing
remote references and remote calls

remote references has Future and RemoteChannel

A remote call returns a Future to its result

In [88]:
# start with 'julia -p 2'
# let process 2 to construct a 2-by-2 random matrix
# rc = remotecall(rand, 2, 2, 2)
# println(fetch(rc))

# Multi-dimensional Arrays
Column first storage in Julia, not row first in C

## construct fuctions
zeros ones trues falses rand randn range

In [89]:
f0 = zeros(8)

8-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [90]:
i0 = zeros(Int32, 8)

8-element Array{Int32,1}:
 0
 0
 0
 0
 0
 0
 0
 0

In [91]:
A = reshape(f0, 2, 4)

2×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [92]:
length(f0), ndims(f0), size(f0), axes(f0)

(8, 1, (8,), (Base.OneTo(8),))

In [93]:
length(A), ndims(A), size(A), axes(A)

(8, 2, (2, 4), (Base.OneTo(2), Base.OneTo(4)))

In [94]:
R = rand(3, 4)

3×4 Array{Float64,2}:
 0.723378  0.575545  0.490903   0.0430735
 0.246339  0.128205  0.0850296  0.987457 
 0.819944  0.932371  0.48747    0.926603 

In [95]:
A = reshape(range(1,stop=8), 4, 2)

4×2 reshape(::UnitRange{Int64}, 4, 2) with eltype Int64:
 1  5
 2  6
 3  7
 4  8

## concatenate
cat vcat hcat

In [96]:
B = [2 1; 4 6; 7 4; 4 8]

4×2 Array{Int64,2}:
 2  1
 4  6
 7  4
 4  8

In [97]:
# hcat
[A B]

4×4 Array{Int64,2}:
 1  5  2  1
 2  6  4  6
 3  7  7  4
 4  8  4  8

In [98]:
# vcat
[A; B]

8×2 Array{Int64,2}:
 1  5
 2  6
 3  7
 4  8
 2  1
 4  6
 7  4
 4  8

## Comprehensions

In [99]:
r1 = [ 2i+3 for i = R]

3×4 Array{Float64,2}:
 4.44676  4.15109  3.98181  3.08615
 3.49268  3.25641  3.17006  4.97491
 4.63989  4.86474  3.97494  4.85321

In [100]:
sum([1/n^2 for n=1:100])

1.634983900184893

## Indexing

In [101]:
r1[2:3,:]

2×4 Array{Float64,2}:
 3.49268  3.25641  3.17006  4.97491
 4.63989  4.86474  3.97494  4.85321

In [102]:
r1[8]

3.170059198973341

In [103]:
r1[[2,9,4]]

3-element Array{Float64,1}:
 3.4926775444903235
 3.974939735009108 
 4.151090857047181 

In [104]:
# Logical indexing like filter
# same as filter(s->s>4, r1)
r1[map(s->s>4, r1)]

6-element Array{Float64,1}:
 4.446756301844745
 4.639887109302052
 4.151090857047181
 4.864742169509411
 4.974913453921729
 4.853206107066482

In [105]:
filter(s->s>4, r1)

6-element Array{Float64,1}:
 4.446756301844745
 4.639887109302052
 4.151090857047181
 4.864742169509411
 4.974913453921729
 4.853206107066482

In [106]:
for i in eachindex(r1)
    #index i and r1[i]
end

## operators
-, +, *, /, \, ^
==, !=, ≈ (isapprox), ≉

In [107]:
A + B

4×2 Array{Int64,2}:
  3   6
  6  12
 10  11
  8  16

In [108]:
A != B

true

In [109]:
A .== B

4×2 BitArray{2}:
 false  false
 false   true
 false  false
  true   true

In [110]:
A .!= 3

4×2 BitArray{2}:
  true  true
  true  true
 false  true
  true  true

In [111]:
A .* B

4×2 Array{Int64,2}:
  2   5
  8  36
 21  28
 16  64

## Broadcasting

In [112]:
a = rand(2,1); b = rand(2,3);

In [113]:
broadcast(+, a, b)

2×3 Array{Float64,2}:
 0.771396  0.965425  1.51135
 1.85251   1.00911   1.65105

In [114]:
a + b 

DimensionMismatch: DimensionMismatch("dimensions must match")

In [115]:
a .+ b

2×3 Array{Float64,2}:
 0.771396  0.965425  1.51135
 1.85251   1.00911   1.65105