# Install IJulia

[IJulia](https://github.com/JuliaLang/IJulia.jl) is Jupyter kernel for Julia

Install [Julia](https://julialang.org/) firstly, then in Julia REPL
```julia
julia>
using Pkg
Pkg.add("IJulia")
Pkg.build("ZMQ")
Pkg.build("IJulia")
```
and finally start the notebook with ```jupyter notebook```

[Learn Julia in Y minutes](https://learnxinyminutes.com/docs/julia/)

Enjoy!

Julia Version 1.1.0

In [1]:
println("Hello Julia")

Hello Julia


# Julia types

In [2]:
Int,Int8,Int16,Int32,Int64,Int128,UInt,UInt8,UInt16,UInt32,UInt64,UInt128,Float16,Float32,Float64,Inf,NaN,BigInt,BigFloat

(Int64, Int8, Int16, Int32, Int64, Int128, UInt64, UInt8, UInt16, UInt32, UInt64, UInt128, Float16, Float32, Float64, Inf, NaN, BigInt, BigFloat)

In [3]:
typemin(Int), typemax(Int)

(-9223372036854775808, 9223372036854775807)

In [4]:
typeof(1),typeof(0x1),typeof(0x123),typeof(0b101),typeof(2 + 1im),typeof(2 // 3)

(Int64, UInt8, UInt16, UInt8, Complex{Int64}, Rational{Int64})

In [5]:
true, false

(true, false)

In [6]:
x=8
2x^2 - 6.3(x+4) + 5

57.400000000000006

In [7]:
zero(x), zero(Float64)

(0, 0.0)

In [8]:
2 < x < 9

true

In [9]:
gcd(128,48), lcm(128, 48)

(16, 384)

In [10]:
hypot(8,9)

12.041594578792296

In [11]:
# complex
5(1 + 2im)*(2 - 3im)

40 + 5im

In [12]:
# fraction
1 + 6//16

11//8

In [13]:
bitstring(888)

"0000000000000000000000000000000000000000000000000000001101111000"

In [14]:
bitstring(0.3)

"0011111111010011001100110011001100110011001100110011001100110011"

In [15]:
s="julia"
typeof(s), typeof('a')

(String, Char)

In [16]:
"good" > "bye"

true

In [17]:
# based on 1
s[1], s[end], s[2:4]

('j', 'a', "uli")

In [18]:
Int('A'), Char(89)

(65, 'Y')

In [19]:
h = "Hello $s $(3+5)"

"Hello julia 8"

In [20]:
repeat("*",10), length(h)

("**********", 13)

In [21]:
using Printf
@printf "demo %0.2f\n" 5.3

demo 5.30


In [22]:
a = [4,6,8]

3-element Array{Int64,1}:
 4
 6
 8

# Julia function 

In [23]:
function bar(x,y)
  x + y
end

bar (generic function with 1 method)

In [24]:
foo(x,y) = 3x^2 + 8y
foo(3,5)

67

In [25]:
map(x -> x^2 + 2x - 1, [8, 4.5, 3.3])

3-element Array{Float64,1}:
 79.0 
 28.25
 16.49

In [26]:
# mulit line
map([-8, 4, -3, 0]) do x
    if x < 0 && iseven(x)
        return 0
    elseif x == 0
        return 1
    else
        return x
    end
end

4-element Array{Int64,1}:
  0
  4
 -3
  1

In [27]:
z = (x = 1; y = 2; x + y)

3

In [28]:
begin
    x = 1; 
    y = 2;
    if x < y
        x + y
    else
        x * y
    end
end

3

In [29]:
min(x, y) = x < y ? x : y; min(3,4)

3

In [30]:
# error() throw ErrorException
# warn() info()
function factorial(n::Int)
    n == 0 && return 1
    n >= 0 || error("n must be non-negative")
    n * factorial(n-1)
end
factorial(8)

40320

In [31]:
try factorial(-4)
catch e
    println("occur error ", e)
end

occur error ErrorException("n must be non-negative")


In [32]:
sum = 0
# Range
for i = 1:5
    sum += i
end
println(sum)

15


In [33]:
for i in [8,5,3]
    sum += i
end
println(sum)

31


# Julia [Tasks](https://docs.julialang.org/en/v1/manual/control-flow/#man-tasks-1) (aka Coroutines)

In [34]:
function producer(c::Channel)
    put!(c, "start")
    for n = 1:3
        put!(c, 2n)
    end
    put!(c, "stop")
end
c = Channel(producer)
take!(c)

"start"

In [35]:
for x in Channel(producer)
    println(x)
end

start
2
4
6
stop


In [36]:
?put!

search: put! permute! invpermute! pushfirst! permutedims! ispunct permutedims



```
put!(c::Channel, v)
```

Append an item `v` to the channel `c`. Blocks if the channel is full.

For unbuffered channels, blocks until a [`take!`](@ref) is performed by a different task.

!!! compat "Julia 1.1"
    `v` now gets converted to the channel's type with [`convert`](@ref) as `put!` is called.


---

```
put!(rr::Future, v)
```

Store a value to a [`Future`](@ref) `rr`. `Future`s are write-once remote references. A `put!` on an already set `Future` throws an `Exception`. All asynchronous remote calls return `Future`s and set the value to the return value of the call upon completion.

---

```
put!(rr::RemoteChannel, args...)
```

Store a set of values to the [`RemoteChannel`](@ref). If the channel is full, blocks until space is available. Return the first argument.


In [37]:
?take!

search: take! StackOverflowError istaskdone stacktrace StackTraces istaskstarted



```
take!(b::IOBuffer)
```

Obtain the contents of an `IOBuffer` as an array, without copying. Afterwards, the `IOBuffer` is reset to its initial state.

# Examples

```jldoctest
julia> io = IOBuffer();

julia> write(io, "JuliaLang is a GitHub organization.", " It has many members.")
56

julia> String(take!(io))
"JuliaLang is a GitHub organization. It has many members."
```

---

```
take!(c::Channel)
```

Remove and return a value from a [`Channel`](@ref). Blocks until data is available.

For unbuffered channels, blocks until a [`put!`](@ref) is performed by a different task.

---

```
take!(rr::RemoteChannel, args...)
```

Fetch value(s) from a [`RemoteChannel`](@ref) `rr`, removing the value(s) in the process.
